version: 0.0
os: linux

files:
  - source: /
    destination: /home/ubuntu
    overwrite: yes

permissions:
  - object: /home/ubuntu/scripts
    owner: ubuntu
    group: ubuntu

hooks:
  BeforeInstall:
    - location: scripts/stop_server.sh
      timeout: 300
      runas: root

  AfterInstall:
    - location: scripts/restart_server.sh
      timeout: 300
      runas: root