version: 0.0
os: linux

files:
  - source: igojoaManagement-0.0.1-SNAPSHOT.jar
    destination: igojoaManagement-0.0.1-SNAPSHOT.jar
    overwrite: yes

permissions:
  - object: igojoaManagement-0.0.1-SNAPSHOT.jar
    owner: ubuntu
    group: ubuntu

hooks:
  BeforeInstall:
    - location: stop_server.sh
      timeout: 300
      runas: ubuntu

  AfterInstall:
    - location: restart_server.sh
      timeout: 300
      runas: ubuntu
