version: 0.0
os: linux
files:
  - source: build/libs/igojoaManagement-0.0.1-SNAPSHOT.jar
    destination: /home/ubuntu/igojoaManagement-0.0.1-SNAPSHOT.jar
hooks:
  AfterInstall:
    - location: scripts/restart_server.sh
      timeout: 300
      runas: ubuntu