version: 0.0
os: linux

files:
  - source: build/libs/igojoaManagement-0.0.1-SNAPSHOT.jar
    destination: /home/ubuntu/igojoaManagement-0.0.1-SNAPSHOT.jar
    overwrite: yes

permissions:
  - object: /home/ubuntu/igojoaManagement-0.0.1-SNAPSHOT.jar
    owner: ubuntu
    group: ubuntu

hooks:
  BeforeInstall:
    - location: /home/ubuntu/scripts/stop_server.sh
      timeout: 300
      runas: ubuntu

  AfterInstall:
    - location: /home/ubuntu/scripts/restart_server.sh
      timeout: 300
      runas: ubuntu